# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=student
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# External API keys Finnhub for stock data
finnhub.api.url=https://finnhub.io/api/v1/quote
finnhub.api.key=d4irml1r01queuak9j00d4irml1r01queuak9j0g